# env config-map

apiVersion: v1
kind: ConfigMap 
metadata:
  namespace: roboshop
  name: cart
  labels:
    project: roboshop
    environment: dev
    component: cart
    tier: app
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"

---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: roboshop
  name: cart
  labels:
    project: roboshop
    environment: dev
    component: cart
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: cart
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: cart
        tier: app
    spec:
      containers:
        - name: cart
          image: visweshbonam/cart:v1
          envFrom:
          - configMapRef:
              name: cart

          
---

# service

apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: cart
  labels:
    project: roboshop
    environment: dev
    component: cart
    tier: app
spec:
  selector:
    project: roboshop
    environment: dev
    component: cart
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

    