# deployement

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongodb
  labels: #deployment labels
    project: roboshop
    environment: dev
    tier: database
    component: mongodb
spec:
  replicas: 1 # no of pods creating
  selector:
    matchLabels: # These are the labels replica set use to create pod replicas, this should match pod labels
      project: roboshop
      environment: dev
      tier: database
      component: mongodb

  template:
    metadata:
      labels: # these are the labels that replica set search while creating pods
        project: roboshop
        environment: dev
        tier: database
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: visweshbonam/mongodb:v1

---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mongodb
spec:
  selector:
    project: roboshop
    environment: dev
    tier: database
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
