# Secrets

apiVersion: v1
kind: Secret
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mysql
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="

---
# deployment

apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: database
      component: mysql
  
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: database
        component: mysql
    spec:
      containers:
        - name: mysql
          image: visweshbonam/mysql:v1
          envFrom:
          - configMapRef:
              name: mysql



---
# services

apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mysql
spec:
  selector:
     project: roboshop
     environment: dev
     tier: database
     component: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  
