# deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: redis
  labels:
    project: roboshop
    environment: dev
    tier: app
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: app
      component: redis
  
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: app
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0

---

# service

apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: redis
  labels:
    project: roboshop
    environment: dev
    tier: app
    component: redis

spec:
  selector:
    project: roboshop
    environment: dev
    tier: app
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
